/*
Navicat MySQL Data Transfer

Source Server         : db_mysql
Source Server Version : 50644
Source Host           : localhost:3306
Source Database       : tool

Target Server Type    : MYSQL
Target Server Version : 50644
File Encoding         : 65001

Date: 2019-12-01 15:25:34
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for 字段信息
-- ----------------------------
DROP TABLE IF EXISTS `字段信息`;
CREATE TABLE `字段信息` (
  `tableid` int(11) NOT NULL,
  `序号` int(11) NOT NULL,
  `字段名称` varchar(255) DEFAULT NULL,
  `字段标识` varchar(255) DEFAULT NULL,
  `类型及长度` varchar(255) DEFAULT NULL,
  `是否允许空值` varchar(255) DEFAULT NULL,
  `计量单位` varchar(255) DEFAULT NULL,
  `主键` varchar(255) DEFAULT NULL,
  `外键` varchar(255) DEFAULT NULL,
  `主键序号` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`tableid`,`序号`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of 字段信息
-- ----------------------------
INSERT INTO `字段信息` VALUES ('175', '1', '时间	', 'TM	', 'DATE	', 'N	', '-	', 'Y	', '-	', '1');
INSERT INTO `字段信息` VALUES ('175', '2', '区镇	', 'AD	', 'C(18)	', 'N	', '-	', 'Y	', 'Y	', '2');
INSERT INTO `字段信息` VALUES ('175', '3', '年用水总量	', 'YWA	', 'N(16,3)	', '-	', '104m3	', '-	', '-	', '-');
INSERT INTO `字段信息` VALUES ('175', '4', '万元GDP年用水量	', 'YWA_GDP_1	', 'N(16,3)	', '-	', 'm3	', '-	', '-	', '-');
INSERT INTO `字段信息` VALUES ('175', '5', '万元GDP增加值年用水量	', 'YWA_GDP_2	', 'N(16,3)	', '-	', 'm3	', '-	', '-	', '-');
INSERT INTO `字段信息` VALUES ('176', '1', '气象测站代码	', 'ST_CODE	', 'C(18)	', '-	', '-	', 'Y	', '-	', '-');
INSERT INTO `字段信息` VALUES ('176', '2', '气象测站名称	', 'ST_NAME	', 'VC(100)	', '-	', '-	', '-	', '-	', '-');
INSERT INTO `字段信息` VALUES ('176', '3', '对象建立时间	', 'FROM_DATE	', 'DATE	', '-	', '-	', '-	', '-	', '-');
INSERT INTO `字段信息` VALUES ('176', '4', '对象终止时间	', 'TO_DATE	', 'DATE	', '-	', '-	', '-	', '-	', '-');

-- ----------------------------
-- Table structure for 数据说明
-- ----------------------------
DROP TABLE IF EXISTS `数据说明`;
CREATE TABLE `数据说明` (
  `id` int(11) NOT NULL,
  `database` varchar(255) DEFAULT NULL,
  `tablename` varchar(255) DEFAULT NULL,
  `tableflag` varchar(255) DEFAULT NULL,
  `tableinf` varchar(255) DEFAULT NULL,
  `zdinf` varchar(255) DEFAULT NULL,
  `html` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of 数据说明
-- ----------------------------
INSERT INTO `数据说明` VALUES ('175', '社会经济数据库', '取水量社会信息表', 'HDP_WASCL_S', 'a) 取水量社会信息表用于存储取水量社会信息。\nb) 表标识为HDP_WASCL_S。\nc) 表号为010205010203。\nd) 各字段定义见下表：\n', '1)	时间：取用水截至时间。\n2)	区镇：区镇代码。\n3)	年用水总量：年用水总量。\n4)	万元GDP年用水量：万元GDP年用水量。\n5)	万年GDP增加值年用水量：万年GDP增加值年用水量。\n', '<p style=\"text-indent:0\">a) 取水量社会信息表用于存储取水量社会信息。</p><p style=\"text-indent:0\">b) 表标识为HDP_WASCL_S。</p><p style=\"text-indent:0\">c) 表号为010205010203。</p><p style=\"text-indent:0\">d) 各字段定义见下表：</p><table width=\"617\"><tbody><tr style=\";height:19px\" class=\"firstRow\"><td width=\"47\" style=\"border: 1px solid windowtext; background: rgb(191, 191, 191); padding: 0px 7px;\"><p>序号</p></td><td width=\"112\" style=\"border-top: 1px solid windowtext; border-right: 1px solid windowtext; border-bottom: 1px solid windowtext; border-image: initial; border-left: none; background: rgb(191, 191, 191); padding: 0px 7px;\"><p><span style=\"color:black\">字段名</span></p></td><td width=\"116\" style=\"border-top: 1px solid windowtext; border-right: 1px solid windowtext; border-bottom: 1px solid windowtext; border-image: initial; border-left: none; background: rgb(191, 191, 191); padding: 0px 7px;\"><p><span style=\"color:black\">字段标识</span></p></td><td width=\"62\" style=\"border-top: 1px solid windowtext; border-right: 1px solid windowtext; border-bottom: 1px solid windowtext; border-image: initial; border-left: none; background: rgb(191, 191, 191); padding: 0px 7px;\"><p><span style=\"color:black\">类型及长度</span></p></td><td width=\"67\" style=\"border-top: 1px solid windowtext; border-right: 1px solid windowtext; border-bottom: 1px solid windowtext; border-image: initial; border-left: none; background: rgb(191, 191, 191); padding: 0px 7px;\"><p><span style=\"color:black\">是否允许空值</span></p></td><td width=\"62\" style=\"border-top: 1px solid windowtext; border-right: 1px solid windowtext; border-bottom: 1px solid windowtext; border-image: initial; border-left: none; background: rgb(191, 191, 191); padding: 0px 7px;\"><p><span style=\"color:black\">计量单位</span></p></td><td width=\"47\" style=\"border-top: 1px solid windowtext; border-right: 1px solid windowtext; border-bottom: 1px solid windowtext; border-image: initial; border-left: none; background: rgb(191, 191, 191); padding: 0px 7px;\"><p><span style=\"color:black\">主键</span></p></td><td width=\"44\" style=\"border-top: 1px solid windowtext; border-right: 1px solid windowtext; border-bottom: 1px solid windowtext; border-image: initial; border-left: none; background: rgb(191, 191, 191); padding: 0px 7px;\"><p><span style=\"color:black\">外键</span></p></td><td width=\"59\" style=\"border-top: 1px solid windowtext; border-right: 1px solid windowtext; border-bottom: 1px solid windowtext; border-image: initial; border-left: none; background: rgb(191, 191, 191); padding: 0px 7px;\"><p><span style=\"color:black\">主键序号</span></p></td></tr><tr style=\";height:19px\"><td width=\"47\" style=\"border-right: 1px solid windowtext; border-bottom: 1px solid windowtext; border-left: 1px solid windowtext; border-image: initial; border-top: none; padding: 0px 7px;\"><p>1</p></td><td width=\"112\" valign=\"bottom\" style=\"border-top: none; border-left: none; border-bottom: 1px solid windowtext; border-right: 1px solid windowtext; padding: 0px 7px;\"><p>时间</p></td><td width=\"116\" style=\"border-top: none; border-left: none; border-bottom: 1px solid windowtext; border-right: 1px solid windowtext; padding: 0px 7px;\"><p>TM</p></td><td width=\"62\" style=\"border-top: none; border-left: none; border-bottom: 1px solid windowtext; border-right: 1px solid windowtext; padding: 0px 7px;\"><p>DATE</p></td><td width=\"67\" style=\"border-top: none; border-left: none; border-bottom: 1px solid windowtext; border-right: 1px solid windowtext; padding: 0px 7px;\"><p>N</p></td><td width=\"62\" style=\"border-top: none; border-left: none; border-bottom: 1px solid windowtext; border-right: 1px solid windowtext; padding: 0px 7px;\"><br/></td><td width=\"47\" style=\"border-top: none; border-left: none; border-bottom: 1px solid windowtext; border-right: 1px solid windowtext; padding: 0px 7px;\"><p>Y</p></td><td width=\"44\" style=\"border-top: none; border-left: none; border-bottom: 1px solid windowtext; border-right: 1px solid windowtext; padding: 0px 7px;\"><br/></td><td width=\"59\" style=\"border-top: none; border-left: none; border-bottom: 1px solid windowtext; border-right: 1px solid windowtext; padding: 0px 7px;\"><p>1</p></td></tr><tr style=\";height:19px\"><td width=\"47\" style=\"border-right: 1px solid windowtext; border-bottom: 1px solid windowtext; border-left: 1px solid windowtext; border-image: initial; border-top: none; padding: 0px 7px;\"><p>2</p></td><td width=\"112\" valign=\"bottom\" style=\"border-top: none; border-left: none; border-bottom: 1px solid windowtext; border-right: 1px solid windowtext; padding: 0px 7px;\"><p>区镇</p></td><td width=\"116\" style=\"border-top: none; border-left: none; border-bottom: 1px solid windowtext; border-right: 1px solid windowtext; padding: 0px 7px;\"><p>AD</p></td><td width=\"62\" style=\"border-top: none; border-left: none; border-bottom: 1px solid windowtext; border-right: 1px solid windowtext; padding: 0px 7px;\"><p>C(18)</p></td><td width=\"67\" style=\"border-top: none; border-left: none; border-bottom: 1px solid windowtext; border-right: 1px solid windowtext; padding: 0px 7px;\"><p>N</p></td><td width=\"62\" style=\"border-top: none; border-left: none; border-bottom: 1px solid windowtext; border-right: 1px solid windowtext; padding: 0px 7px;\"><br/></td><td width=\"47\" style=\"border-top: none; border-left: none; border-bottom: 1px solid windowtext; border-right: 1px solid windowtext; padding: 0px 7px;\"><p>Y</p></td><td width=\"44\" style=\"border-top: none; border-left: none; border-bottom: 1px solid windowtext; border-right: 1px solid windowtext; padding: 0px 7px;\"><p>Y</p></td><td width=\"59\" style=\"border-top: none; border-left: none; border-bottom: 1px solid windowtext; border-right: 1px solid windowtext; padding: 0px 7px;\"><p>2</p></td></tr><tr style=\";height:19px\"><td width=\"47\" style=\"border-right: 1px solid windowtext; border-bottom: 1px solid windowtext; border-left: 1px solid windowtext; border-image: initial; border-top: none; padding: 0px 7px;\"><p>3</p></td><td width=\"112\" valign=\"bottom\" style=\"border-top: none; border-left: none; border-bottom: 1px solid windowtext; border-right: 1px solid windowtext; padding: 0px 7px;\"><p>年用水总量</p></td><td width=\"116\" style=\"border-top: none; border-left: none; border-bottom: 1px solid windowtext; border-right: 1px solid windowtext; padding: 0px 7px;\"><p>YWA</p></td><td width=\"62\" style=\"border-top: none; border-left: none; border-bottom: 1px solid windowtext; border-right: 1px solid windowtext; padding: 0px 7px;\"><p>N(16,3)</p></td><td width=\"67\" style=\"border-top: none; border-left: none; border-bottom: 1px solid windowtext; border-right: 1px solid windowtext; padding: 0px 7px;\"><br/></td><td width=\"62\" style=\"border-top: none; border-left: none; border-bottom: 1px solid windowtext; border-right: 1px solid windowtext; padding: 0px 7px;\"><p>104m3</p></td><td width=\"47\" style=\"border-top: none; border-left: none; border-bottom: 1px solid windowtext; border-right: 1px solid windowtext; padding: 0px 7px;\"><br/></td><td width=\"44\" style=\"border-top: none; border-left: none; border-bottom: 1px solid windowtext; border-right: 1px solid windowtext; padding: 0px 7px;\"><br/></td><td width=\"59\" style=\"border-top: none; border-left: none; border-bottom: 1px solid windowtext; border-right: 1px solid windowtext; padding: 0px 7px;\"><br/></td></tr><tr style=\";height:19px\"><td width=\"47\" style=\"border-right: 1px solid windowtext; border-bottom: 1px solid windowtext; border-left: 1px solid windowtext; border-image: initial; border-top: none; padding: 0px 7px;\"><p>4</p></td><td width=\"112\" valign=\"bottom\" style=\"border-top: none; border-left: none; border-bottom: 1px solid windowtext; border-right: 1px solid windowtext; padding: 0px 7px;\"><p>万元GDP年用水量</p></td><td width=\"116\" style=\"border-top: none; border-left: none; border-bottom: 1px solid windowtext; border-right: 1px solid windowtext; padding: 0px 7px;\"><p>YWA_GDP_1</p></td><td width=\"62\" style=\"border-top: none; border-left: none; border-bottom: 1px solid windowtext; border-right: 1px solid windowtext; padding: 0px 7px;\"><p>N(16,3)</p></td><td width=\"67\" style=\"border-top: none; border-left: none; border-bottom: 1px solid windowtext; border-right: 1px solid windowtext; padding: 0px 7px;\"><br/></td><td width=\"62\" style=\"border-top: none; border-left: none; border-bottom: 1px solid windowtext; border-right: 1px solid windowtext; padding: 0px 7px;\"><p>m3</p></td><td width=\"47\" style=\"border-top: none; border-left: none; border-bottom: 1px solid windowtext; border-right: 1px solid windowtext; padding: 0px 7px;\"><br/></td><td width=\"44\" style=\"border-top: none; border-left: none; border-bottom: 1px solid windowtext; border-right: 1px solid windowtext; padding: 0px 7px;\"><br/></td><td width=\"59\" style=\"border-top: none; border-left: none; border-bottom: 1px solid windowtext; border-right: 1px solid windowtext; padding: 0px 7px;\"><br/></td></tr><tr style=\";height:19px\"><td width=\"47\" style=\"border-right: 1px solid windowtext; border-bottom: 1px solid windowtext; border-left: 1px solid windowtext; border-image: initial; border-top: none; padding: 0px 7px;\"><p>5</p></td><td width=\"112\" valign=\"bottom\" style=\"border-top: none; border-left: none; border-bottom: 1px solid windowtext; border-right: 1px solid windowtext; padding: 0px 7px;\"><p>万元GDP增加值年用水量</p></td><td width=\"116\" style=\"border-top: none; border-left: none; border-bottom: 1px solid windowtext; border-right: 1px solid windowtext; padding: 0px 7px;\"><p>YWA_GDP_2</p></td><td width=\"62\" style=\"border-top: none; border-left: none; border-bottom: 1px solid windowtext; border-right: 1px solid windowtext; padding: 0px 7px;\"><p>N(16,3)</p></td><td width=\"67\" style=\"border-top: none; border-left: none; border-bottom: 1px solid windowtext; border-right: 1px solid windowtext; padding: 0px 7px;\"><br/></td><td width=\"62\" style=\"border-top: none; border-left: none; border-bottom: 1px solid windowtext; border-right: 1px solid windowtext; padding: 0px 7px;\"><p>m3</p></td><td width=\"47\" style=\"border-top: none; border-left: none; border-bottom: 1px solid windowtext; border-right: 1px solid windowtext; padding: 0px 7px;\"><br/></td><td width=\"44\" style=\"border-top: none; border-left: none; border-bottom: 1px solid windowtext; border-right: 1px solid windowtext; padding: 0px 7px;\"><br/></td><td width=\"59\" style=\"border-top: none; border-left: none; border-bottom: 1px solid windowtext; border-right: 1px solid windowtext; padding: 0px 7px;\"><br/></td></tr></tbody></table><p style=\"text-indent:0\">e) 各字段说明如下：</p><p>1)<span style=\"font:9px &#39;Times New Roman&#39;\">&nbsp;&nbsp; </span><span style=\"font-family:等线\">时间：取用水截至时间。</span></p><p>2)<span style=\"font:9px &#39;Times New Roman&#39;\">&nbsp;&nbsp; </span><span style=\"font-family:等线\">区镇：区镇代码。</span></p><p>3)<span style=\"font:9px &#39;Times New Roman&#39;\">&nbsp;&nbsp; </span><span style=\"font-family:等线\">年用水总量：年用水总量。</span></p><p>4)<span style=\"font:9px &#39;Times New Roman&#39;\">&nbsp;&nbsp; </span><span style=\"font-family:等线\">万元</span>GDP<span style=\"font-family:等线\">年用水量：万元</span>GDP<span style=\"font-family: 等线\">年用水量。</span></p><p>5)<span style=\"font:9px &#39;Times New Roman&#39;\">&nbsp;&nbsp; </span><span style=\"font-family:等线\">万年</span>GDP<span style=\"font-family:等线\">增加值年用水量：万年</span>GDP<span style=\"font-family: 等线\">增加值年用水量。</span></p><p><br/></p>');
INSERT INTO `数据说明` VALUES ('176', '社会经济数据库', '气象测站名录表', 'OBJ_QXST', 'a) 气象测站名录表用于存储气象测站名录。\nb) 表标识为OBJ_QXST。\nc) 表号为990101010000。\nd) 各字段定义见下表：\n        ', '1)	气象测站代码：全国范围内唯一代表某个测站的编码，按《水利对象分类与编码总则》的规定执行，18位定长字符串。\n2)	气象测站名称：测站的中文名称。\n3)	对象建立时间：对象个体生命周期开始时间，对于无法获取生命周期开始时间的对象，采用该对象名录信息的首次入库时间。\n4)	对象终止时间：对象个体生命周期终止时间，或本对象名录在此数据库中的停用时间。\n ', null);

-- ----------------------------
-- Table structure for 资源目录
-- ----------------------------
DROP TABLE IF EXISTS `资源目录`;
CREATE TABLE `资源目录` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `parent` varchar(255) NOT NULL,
  `text` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=665 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of 资源目录
-- ----------------------------
INSERT INTO `资源目录` VALUES ('35', '#', '基础数据库');
INSERT INTO `资源目录` VALUES ('36', '#', '业务共享数据库');
INSERT INTO `资源目录` VALUES ('37', '35', '社会经济数据库');
INSERT INTO `资源目录` VALUES ('38', '35', '水利基础数据库');
INSERT INTO `资源目录` VALUES ('39', '35', '水利行业单位数据库');
INSERT INTO `资源目录` VALUES ('40', '35', '管理制度');
INSERT INTO `资源目录` VALUES ('41', '35', '规范标准');
INSERT INTO `资源目录` VALUES ('42', '36', '监测数据库');
INSERT INTO `资源目录` VALUES ('43', '36', '业务管理数据库');
INSERT INTO `资源目录` VALUES ('44', '36', '政务管理数据库');
INSERT INTO `资源目录` VALUES ('45', '37', '社会经济统计数据');
INSERT INTO `资源目录` VALUES ('46', '38', '河流湖泊');
INSERT INTO `资源目录` VALUES ('47', '38', '水利工程数据');
INSERT INTO `资源目录` VALUES ('48', '38', '水务设施数据');
INSERT INTO `资源目录` VALUES ('49', '38', '管理区划数据');
INSERT INTO `资源目录` VALUES ('50', '38', '管理单元数据');
INSERT INTO `资源目录` VALUES ('51', '38', '管理对象数据');
INSERT INTO `资源目录` VALUES ('52', '39', '水利行业单位数据');
INSERT INTO `资源目录` VALUES ('53', '40', '管理制度数据');
INSERT INTO `资源目录` VALUES ('54', '41', '规范标准数据');
INSERT INTO `资源目录` VALUES ('55', '42', '河流湖泊监测数据');
INSERT INTO `资源目录` VALUES ('56', '42', '水利工程监测数据');
INSERT INTO `资源目录` VALUES ('57', '42', '水利管理活动监测数据');
INSERT INTO `资源目录` VALUES ('58', '42', '其他部门监测数据');
INSERT INTO `资源目录` VALUES ('59', '43', '防汛防台业务管理数据');
INSERT INTO `资源目录` VALUES ('60', '43', '水利工程安全运行数据');
INSERT INTO `资源目录` VALUES ('61', '43', '水工程建设数据');
INSERT INTO `资源目录` VALUES ('62', '43', '水资源开发利用管理数据');
INSERT INTO `资源目录` VALUES ('63', '43', '节水管理数据');
INSERT INTO `资源目录` VALUES ('64', '43', '江河湖泊管理数据');
INSERT INTO `资源目录` VALUES ('65', '43', '水土保持管理数据');
INSERT INTO `资源目录` VALUES ('66', '43', '水利监督管理');
INSERT INTO `资源目录` VALUES ('67', '44', '政务数据');
INSERT INTO `资源目录` VALUES ('68', '45', '取水量数据');
INSERT INTO `资源目录` VALUES ('69', '45', '气象测站QXST');
INSERT INTO `资源目录` VALUES ('70', '46', '流域BAS');
INSERT INTO `资源目录` VALUES ('71', '46', '河流RV');
INSERT INTO `资源目录` VALUES ('72', '46', '湖泊LK');
INSERT INTO `资源目录` VALUES ('73', '47', '测站ST');
INSERT INTO `资源目录` VALUES ('74', '47', '水闸WAGA');
INSERT INTO `资源目录` VALUES ('75', '47', '泵站PUST');
INSERT INTO `资源目录` VALUES ('76', '47', '堤防DIKE');
INSERT INTO `资源目录` VALUES ('77', '47', '圩垸POLD');
INSERT INTO `资源目录` VALUES ('78', '47', '涵洞CULV');
INSERT INTO `资源目录` VALUES ('79', '47', '水库DAM');
INSERT INTO `资源目录` VALUES ('80', '47', '灌区IRR');
INSERT INTO `资源目录` VALUES ('81', '47', '护岸护坡RVT');
INSERT INTO `资源目录` VALUES ('82', '47', '视频监控点VDSV');
INSERT INTO `资源目录` VALUES ('83', '48', '自来水厂WAWO');
INSERT INTO `资源目录` VALUES ('84', '48', '污水处理厂STP');
INSERT INTO `资源目录` VALUES ('85', '48', '农村生活污水处理设施CDSTF');
INSERT INTO `资源目录` VALUES ('86', '49', '水资源分区WRZ');
INSERT INTO `资源目录` VALUES ('87', '49', '地表水功能区WFZ');
INSERT INTO `资源目录` VALUES ('88', '49', '地下水功能区GWFZ');
INSERT INTO `资源目录` VALUES ('89', '49', '采砂分区SEP');
INSERT INTO `资源目录` VALUES ('90', '49', '地表水水源地SWHS');
INSERT INTO `资源目录` VALUES ('91', '49', '地下水水源地GWHS');
INSERT INTO `资源目录` VALUES ('92', '49', '河段REA');
INSERT INTO `资源目录` VALUES ('93', '49', '堤段DISC');
INSERT INTO `资源目录` VALUES ('94', '49', '险工隐患');
INSERT INTO `资源目录` VALUES ('95', '49', '河道断面RISE');
INSERT INTO `资源目录` VALUES ('96', '49', '行政区划AD');
INSERT INTO `资源目录` VALUES ('97', '50', '地表水取水口WAIN');
INSERT INTO `资源目录` VALUES ('98', '50', '地下水取水井WELL');
INSERT INTO `资源目录` VALUES ('99', '50', '地下水监测井GWMW');
INSERT INTO `资源目录` VALUES ('100', '50', '退水排污口PDO');
INSERT INTO `资源目录` VALUES ('101', '50', '水域岸线SHLNM');
INSERT INTO `资源目录` VALUES ('102', '50', '水质考核断面EMSC');
INSERT INTO `资源目录` VALUES ('103', '50', '施工坝CDM');
INSERT INTO `资源目录` VALUES ('104', '50', '路卡RDBK');
INSERT INTO `资源目录` VALUES ('105', '50', '码头JTY');
INSERT INTO `资源目录` VALUES ('106', '50', '建（构）筑物BD');
INSERT INTO `资源目录` VALUES ('107', '50', '桥梁BRID');
INSERT INTO `资源目录` VALUES ('108', '50', '管线PIPE');
INSERT INTO `资源目录` VALUES ('109', '51', '取用水户WIU');
INSERT INTO `资源目录` VALUES ('110', '51', '退排水户DRHO');
INSERT INTO `资源目录` VALUES ('111', '51', '涉水组织机构RIUN');
INSERT INTO `资源目录` VALUES ('112', '51', '岸线占用单位COU');
INSERT INTO `资源目录` VALUES ('113', '51', '水事案件SSAJ');
INSERT INTO `资源目录` VALUES ('114', '51', '自然人PERS');
INSERT INTO `资源目录` VALUES ('115', '52', '水利行业单位WIUN');
INSERT INTO `资源目录` VALUES ('116', '53', '管理制度数据');
INSERT INTO `资源目录` VALUES ('117', '54', '规范标准数据');
INSERT INTO `资源目录` VALUES ('118', '55', '降水监测');
INSERT INTO `资源目录` VALUES ('119', '55', '水位监测');
INSERT INTO `资源目录` VALUES ('120', '55', '断面水质监测');
INSERT INTO `资源目录` VALUES ('121', '55', '灌区用水监测');
INSERT INTO `资源目录` VALUES ('122', '55', '地下水监测');
INSERT INTO `资源目录` VALUES ('123', '55', '水功能区监测');
INSERT INTO `资源目录` VALUES ('124', '55', '积水点监测');
INSERT INTO `资源目录` VALUES ('125', '56', '水闸');
INSERT INTO `资源目录` VALUES ('126', '56', '泵站');
INSERT INTO `资源目录` VALUES ('127', '56', '堤防');
INSERT INTO `资源目录` VALUES ('128', '56', '圩垸');
INSERT INTO `资源目录` VALUES ('129', '56', '涵洞');
INSERT INTO `资源目录` VALUES ('130', '56', '水库');
INSERT INTO `资源目录` VALUES ('131', '56', '堤段');
INSERT INTO `资源目录` VALUES ('132', '57', '取用水监测');
INSERT INTO `资源目录` VALUES ('133', '57', '退排水监测');
INSERT INTO `资源目录` VALUES ('134', '57', '地下水取水井监测');
INSERT INTO `资源目录` VALUES ('135', '57', '自来水监测');
INSERT INTO `资源目录` VALUES ('136', '57', '水务设施运行监测');
INSERT INTO `资源目录` VALUES ('137', '58', '气象监测数据');
INSERT INTO `资源目录` VALUES ('138', '59', '预测预报管理');
INSERT INTO `资源目录` VALUES ('139', '59', '防汛防台调度管理');
INSERT INTO `资源目录` VALUES ('140', '59', '积水点WP');
INSERT INTO `资源目录` VALUES ('141', '59', '测站维护');
INSERT INTO `资源目录` VALUES ('142', '59', '应急抢险技术支持管理');
INSERT INTO `资源目录` VALUES ('143', '60', '水闸');
INSERT INTO `资源目录` VALUES ('144', '60', '泵站');
INSERT INTO `资源目录` VALUES ('145', '60', '堤防');
INSERT INTO `资源目录` VALUES ('146', '60', '堤段');
INSERT INTO `资源目录` VALUES ('147', '61', '水利、水务规划计划');
INSERT INTO `资源目录` VALUES ('148', '61', '水利、水务工程施工管理');
INSERT INTO `资源目录` VALUES ('149', '62', '取用水管理数据');
INSERT INTO `资源目录` VALUES ('150', '62', '水资源管理');
INSERT INTO `资源目录` VALUES ('151', '62', '水资源保护');
INSERT INTO `资源目录` VALUES ('152', '63', '节水管理数据');
INSERT INTO `资源目录` VALUES ('153', '63', '节水政策标准与推广引导数据');
INSERT INTO `资源目录` VALUES ('154', '64', '河长制管理数据');
INSERT INTO `资源目录` VALUES ('155', '64', '水域岸线管理数据');
INSERT INTO `资源目录` VALUES ('156', '64', '河道管护');
INSERT INTO `资源目录` VALUES ('157', '64', '河道采砂管理数据');
INSERT INTO `资源目录` VALUES ('158', '64', '建、构筑物管理');
INSERT INTO `资源目录` VALUES ('159', '64', '河道保洁RVCLN');
INSERT INTO `资源目录` VALUES ('160', '64', '水利桥梁监管');
INSERT INTO `资源目录` VALUES ('161', '64', '路卡');
INSERT INTO `资源目录` VALUES ('162', '65', '生产建设活动监督管理');
INSERT INTO `资源目录` VALUES ('163', '66', '安全生产监管数据');
INSERT INTO `资源目录` VALUES ('164', '66', '水行政执法数据');
INSERT INTO `资源目录` VALUES ('165', '66', '许可审批');
INSERT INTO `资源目录` VALUES ('166', '67', '综合办公');
INSERT INTO `资源目录` VALUES ('167', '67', '财务与审计');
INSERT INTO `资源目录` VALUES ('168', '67', '组织人事');
INSERT INTO `资源目录` VALUES ('169', '67', '科技管理');
INSERT INTO `资源目录` VALUES ('170', '67', '纪检监察');
INSERT INTO `资源目录` VALUES ('171', '67', '安全监督');
INSERT INTO `资源目录` VALUES ('172', '67', '机关管理');
INSERT INTO `资源目录` VALUES ('173', '67', '测绘测量');
INSERT INTO `资源目录` VALUES ('174', '67', '水利普查');
INSERT INTO `资源目录` VALUES ('175', '68', '取水量社会信息表');
INSERT INTO `资源目录` VALUES ('176', '69', '气象测站名录表');
INSERT INTO `资源目录` VALUES ('177', '69', '气象测站基础信息表');
INSERT INTO `资源目录` VALUES ('178', '70', '流域名录表');
INSERT INTO `资源目录` VALUES ('179', '70', '流域基础信息表');
INSERT INTO `资源目录` VALUES ('180', '70', '流域与行政区划关系表');
INSERT INTO `资源目录` VALUES ('181', '70', '流域与上级流域关系表');
INSERT INTO `资源目录` VALUES ('182', '70', '流域与水资源分区关系表');
INSERT INTO `资源目录` VALUES ('183', '71', '河流名录表');
INSERT INTO `资源目录` VALUES ('184', '71', '河流基础信息表');
INSERT INTO `资源目录` VALUES ('185', '71', '河流河源位置表');
INSERT INTO `资源目录` VALUES ('186', '71', '河流河口位置表');
INSERT INTO `资源目录` VALUES ('187', '71', '河流流经区县表');
INSERT INTO `资源目录` VALUES ('188', '71', '河流所属流域表');
INSERT INTO `资源目录` VALUES ('189', '71', '河流上下级关系表');
INSERT INTO `资源目录` VALUES ('190', '72', '湖泊名录表');
INSERT INTO `资源目录` VALUES ('191', '72', '湖泊基础信息表');
INSERT INTO `资源目录` VALUES ('192', '72', '湖泊所属区县表');
INSERT INTO `资源目录` VALUES ('193', '72', '湖泊所在流域表');
INSERT INTO `资源目录` VALUES ('194', '72', '湖泊所在水资源分区表');
INSERT INTO `资源目录` VALUES ('195', '72', '湖泊出入河流表');
INSERT INTO `资源目录` VALUES ('196', '72', '湖泊管理单位表');
INSERT INTO `资源目录` VALUES ('197', '73', '测站名录表');
INSERT INTO `资源目录` VALUES ('198', '73', '测站基本属性表');
INSERT INTO `资源目录` VALUES ('199', '74', '水闸名录表');
INSERT INTO `资源目录` VALUES ('200', '74', '水闸基础信息表');
INSERT INTO `资源目录` VALUES ('201', '74', '水闸所在位置表');
INSERT INTO `资源目录` VALUES ('202', '74', '水闸所在流域表');
INSERT INTO `资源目录` VALUES ('203', '74', '水闸所在水资源分区表');
INSERT INTO `资源目录` VALUES ('204', '74', '水闸所在河流表');
INSERT INTO `资源目录` VALUES ('205', '74', '水闸所在湖泊表');
INSERT INTO `资源目录` VALUES ('206', '74', '水闸所属水库表');
INSERT INTO `资源目录` VALUES ('207', '74', '水闸所在堤防表');
INSERT INTO `资源目录` VALUES ('208', '74', '水闸所在渠道表');
INSERT INTO `资源目录` VALUES ('209', '74', '水闸所属圩垸表');
INSERT INTO `资源目录` VALUES ('210', '74', '水闸所属灌区表');
INSERT INTO `资源目录` VALUES ('211', '74', '水闸所属引调水工程表');
INSERT INTO `资源目录` VALUES ('212', '74', '水闸所属蓄滞洪区表');
INSERT INTO `资源目录` VALUES ('213', '74', '水闸管理单位表');
INSERT INTO `资源目录` VALUES ('214', '75', '泵站名录表');
INSERT INTO `资源目录` VALUES ('215', '75', '泵站基础信息表');
INSERT INTO `资源目录` VALUES ('216', '75', '泵站所在位置表');
INSERT INTO `资源目录` VALUES ('217', '75', '泵站所在流域表');
INSERT INTO `资源目录` VALUES ('218', '75', '泵站所在水资源分区表');
INSERT INTO `资源目录` VALUES ('219', '75', '泵站所在河流表');
INSERT INTO `资源目录` VALUES ('220', '75', '泵站所在湖泊表');
INSERT INTO `资源目录` VALUES ('221', '75', '泵站所属水库表');
INSERT INTO `资源目录` VALUES ('222', '75', '泵站所属水闸表');
INSERT INTO `资源目录` VALUES ('223', '75', '泵站所在堤防表');
INSERT INTO `资源目录` VALUES ('224', '75', '泵站所在渠道表');
INSERT INTO `资源目录` VALUES ('225', '75', '泵站所属灌区表');
INSERT INTO `资源目录` VALUES ('226', '75', '泵站所属引调水表');
INSERT INTO `资源目录` VALUES ('227', '75', '泵站管理单位表');
INSERT INTO `资源目录` VALUES ('228', '76', '堤防名录表');
INSERT INTO `资源目录` VALUES ('229', '76', '堤防基础信息表');
INSERT INTO `资源目录` VALUES ('230', '76', '堤防起点所在位置表');
INSERT INTO `资源目录` VALUES ('231', '76', '堤防终点所在位置表');
INSERT INTO `资源目录` VALUES ('232', '76', '堤防涉及区县表');
INSERT INTO `资源目录` VALUES ('233', '76', '堤防所在流域表');
INSERT INTO `资源目录` VALUES ('234', '76', '堤防所在水资源分区表');
INSERT INTO `资源目录` VALUES ('235', '76', '堤防所在河流表');
INSERT INTO `资源目录` VALUES ('236', '76', '堤防所在湖泊表');
INSERT INTO `资源目录` VALUES ('237', '76', '堤防所属圩垸表');
INSERT INTO `资源目录` VALUES ('238', '76', '堤防所属蓄滞洪区表');
INSERT INTO `资源目录` VALUES ('239', '76', '堤防管理单位表');
INSERT INTO `资源目录` VALUES ('240', '77', '圩垸名录表');
INSERT INTO `资源目录` VALUES ('241', '77', '圩垸基础信息表');
INSERT INTO `资源目录` VALUES ('242', '77', '圩垸所在位置表');
INSERT INTO `资源目录` VALUES ('243', '77', '圩垸所在流域表');
INSERT INTO `资源目录` VALUES ('244', '77', '圩垸所在水资源分区表');
INSERT INTO `资源目录` VALUES ('245', '77', '圩垸管辖单位表');
INSERT INTO `资源目录` VALUES ('246', '78', '涵洞名录表');
INSERT INTO `资源目录` VALUES ('247', '78', '涵洞基础信息表');
INSERT INTO `资源目录` VALUES ('248', '78', '涵洞所在位置表');
INSERT INTO `资源目录` VALUES ('249', '78', '涵洞所在流域表');
INSERT INTO `资源目录` VALUES ('250', '78', '涵洞所在水利分区表');
INSERT INTO `资源目录` VALUES ('251', '78', '涵洞所在河段表');
INSERT INTO `资源目录` VALUES ('252', '78', '涵洞所在堤段表');
INSERT INTO `资源目录` VALUES ('253', '78', '涵洞管理单位表');
INSERT INTO `资源目录` VALUES ('254', '79', '水库名录表');
INSERT INTO `资源目录` VALUES ('255', '79', '水库大坝基础信息表');
INSERT INTO `资源目录` VALUES ('256', '79', '水库基础信息表');
INSERT INTO `资源目录` VALUES ('257', '79', '水库库容曲线表');
INSERT INTO `资源目录` VALUES ('258', '79', '水库主坝所在位置表');
INSERT INTO `资源目录` VALUES ('259', '79', '水库库区涉及区县表');
INSERT INTO `资源目录` VALUES ('260', '79', '水库所在流域表');
INSERT INTO `资源目录` VALUES ('261', '79', '水库所在水资源分区表');
INSERT INTO `资源目录` VALUES ('262', '79', '水库所在河流表');
INSERT INTO `资源目录` VALUES ('263', '79', '水库管理单位表');
INSERT INTO `资源目录` VALUES ('264', '79', '水库大坝所在位置表');
INSERT INTO `资源目录` VALUES ('265', '79', '水库大坝所在河流表');
INSERT INTO `资源目录` VALUES ('266', '79', '水库大坝所属水库表');
INSERT INTO `资源目录` VALUES ('267', '80', '灌区名录表');
INSERT INTO `资源目录` VALUES ('268', '80', '灌区基础信息表');
INSERT INTO `资源目录` VALUES ('269', '80', '灌区涉及区镇表');
INSERT INTO `资源目录` VALUES ('270', '80', '灌区所在流域表');
INSERT INTO `资源目录` VALUES ('271', '80', '灌区所在水资源分区表');
INSERT INTO `资源目录` VALUES ('272', '80', '灌区水源河流表');
INSERT INTO `资源目录` VALUES ('273', '80', '灌区水源水库表');
INSERT INTO `资源目录` VALUES ('274', '80', '灌区水源引调水工程表');
INSERT INTO `资源目录` VALUES ('275', '80', '灌区取水水源取水口表');
INSERT INTO `资源目录` VALUES ('276', '80', '灌区管理单位表');
INSERT INTO `资源目录` VALUES ('277', '81', '护岸护坡基础信息表');
INSERT INTO `资源目录` VALUES ('278', '82', '视频监控点基础信息表');
INSERT INTO `资源目录` VALUES ('279', '83', '自来水厂名录表');
INSERT INTO `资源目录` VALUES ('280', '83', '自来水厂基础信息表');
INSERT INTO `资源目录` VALUES ('281', '83', '自来水厂所在位置表');
INSERT INTO `资源目录` VALUES ('282', '83', '自来水厂所在流域表');
INSERT INTO `资源目录` VALUES ('283', '83', '自来水厂所在水资源分区表');
INSERT INTO `资源目录` VALUES ('284', '83', '自来水厂所有取水口表');
INSERT INTO `资源目录` VALUES ('285', '83', '自来水厂管辖取用水户表');
INSERT INTO `资源目录` VALUES ('286', '84', '污水处理厂名录表');
INSERT INTO `资源目录` VALUES ('287', '84', '污水处理厂基础信息表');
INSERT INTO `资源目录` VALUES ('288', '84', '污水处理厂所在位置表');
INSERT INTO `资源目录` VALUES ('289', '84', '污水处理厂所在流域表');
INSERT INTO `资源目录` VALUES ('290', '84', '污水处理厂所在水资源分区表');
INSERT INTO `资源目录` VALUES ('291', '84', '污水处理厂所有退水排污口表');
INSERT INTO `资源目录` VALUES ('292', '84', '污水处理厂管辖退排水户表');
INSERT INTO `资源目录` VALUES ('293', '84', '污水处理厂管理单位表');
INSERT INTO `资源目录` VALUES ('294', '85', '农村生活污水处理设施基础信息表');
INSERT INTO `资源目录` VALUES ('295', '85', '农村生活污水处理设施所在区镇表');
INSERT INTO `资源目录` VALUES ('296', '85', '农村生活污水处理设施所在流域表');
INSERT INTO `资源目录` VALUES ('297', '85', '农村生活污水处理设施所在河流表');
INSERT INTO `资源目录` VALUES ('298', '85', '农村生活污水处理设施管辖退排水户表');
INSERT INTO `资源目录` VALUES ('299', '85', '农村生活污水处理设施管理单位表');
INSERT INTO `资源目录` VALUES ('300', '85', '农村生活污水处理设施收益村（社区）表');
INSERT INTO `资源目录` VALUES ('301', '85', '农村生活污水处理设施第三方管护单位表');
INSERT INTO `资源目录` VALUES ('302', '86', '水资源分区名录表');
INSERT INTO `资源目录` VALUES ('303', '86', '水资源分区基础信息表');
INSERT INTO `资源目录` VALUES ('304', '87', '地表水功能区名录表');
INSERT INTO `资源目录` VALUES ('305', '87', '地表水功能区基础信息表');
INSERT INTO `资源目录` VALUES ('306', '87', '地表水功能区涉及区镇表');
INSERT INTO `资源目录` VALUES ('307', '87', '地表水功能区所在流域表');
INSERT INTO `资源目录` VALUES ('308', '87', '地表水功能区所在水资源分区表');
INSERT INTO `资源目录` VALUES ('309', '87', '地表水功能区所在河流表');
INSERT INTO `资源目录` VALUES ('310', '87', '地表水功能区所在湖泊表');
INSERT INTO `资源目录` VALUES ('311', '87', '地表水功能区所在水库表');
INSERT INTO `资源目录` VALUES ('312', '87', '地表水功能区起始断面河道断面表');
INSERT INTO `资源目录` VALUES ('313', '87', '地表水功能区终止断面河道断面表');
INSERT INTO `资源目录` VALUES ('314', '87', '地表水功能区监测断面河道断面表');
INSERT INTO `资源目录` VALUES ('315', '87', '地表水功能区所在河段关系表');
INSERT INTO `资源目录` VALUES ('316', '87', '地表水功能区与测站关系表');
INSERT INTO `资源目录` VALUES ('317', '88', '地下水功能区名录表');
INSERT INTO `资源目录` VALUES ('318', '88', '地下水功能区基础信息表');
INSERT INTO `资源目录` VALUES ('319', '88', '地下水功能区涉及区镇表');
INSERT INTO `资源目录` VALUES ('320', '88', '地下水功能区所在流域表');
INSERT INTO `资源目录` VALUES ('321', '88', '地下水功能区所在水资源分区表');
INSERT INTO `资源目录` VALUES ('322', '89', '采砂分区名录表');
INSERT INTO `资源目录` VALUES ('323', '89', '采砂分区基础信息表');
INSERT INTO `资源目录` VALUES ('324', '90', '地表水水源地名录表');
INSERT INTO `资源目录` VALUES ('325', '90', '地表水水源地基础信息表');
INSERT INTO `资源目录` VALUES ('326', '90', '地表水水源地所在位置表');
INSERT INTO `资源目录` VALUES ('327', '90', '地表水水源地所在流域表');
INSERT INTO `资源目录` VALUES ('328', '90', '地表水水源地所在水资源分区表');
INSERT INTO `资源目录` VALUES ('329', '90', '地表水水源地所在河流表');
INSERT INTO `资源目录` VALUES ('330', '90', '地表水水源地水源湖泊表');
INSERT INTO `资源目录` VALUES ('331', '90', '地表水水源地水源水库表');
INSERT INTO `资源目录` VALUES ('332', '90', '地表水水源地所在地表水功能区表');
INSERT INTO `资源目录` VALUES ('333', '90', '地表水水源地管理单位表');
INSERT INTO `资源目录` VALUES ('334', '91', '地下水水源地名录表');
INSERT INTO `资源目录` VALUES ('335', '91', '地下水水源地基础信息表');
INSERT INTO `资源目录` VALUES ('336', '91', '地下水水源地所在位置表');
INSERT INTO `资源目录` VALUES ('337', '91', '地下水水源地所在流域表');
INSERT INTO `资源目录` VALUES ('338', '91', '地下水水源地所在水资源分区表');
INSERT INTO `资源目录` VALUES ('339', '91', '地下水水源地管理单位表');
INSERT INTO `资源目录` VALUES ('340', '92', '河段名录表');
INSERT INTO `资源目录` VALUES ('341', '92', '河段基础信息表');
INSERT INTO `资源目录` VALUES ('342', '92', '河段起点位置表');
INSERT INTO `资源目录` VALUES ('343', '92', '河段终点位置表');
INSERT INTO `资源目录` VALUES ('344', '92', '河段涉及区划表');
INSERT INTO `资源目录` VALUES ('345', '92', '河段所在流域表');
INSERT INTO `资源目录` VALUES ('346', '92', '河段所在水资源分区表');
INSERT INTO `资源目录` VALUES ('347', '92', '河段所在河流表');
INSERT INTO `资源目录` VALUES ('348', '92', '河段管理单位表');
INSERT INTO `资源目录` VALUES ('349', '93', '堤段名录表');
INSERT INTO `资源目录` VALUES ('350', '93', '堤段基础信息表');
INSERT INTO `资源目录` VALUES ('351', '93', '堤段起点位置表');
INSERT INTO `资源目录` VALUES ('352', '93', '堤段终点位置表');
INSERT INTO `资源目录` VALUES ('353', '93', '堤段所属区划表');
INSERT INTO `资源目录` VALUES ('354', '93', '堤段所在流域表');
INSERT INTO `资源目录` VALUES ('355', '93', '堤段所在水资源分区表');
INSERT INTO `资源目录` VALUES ('356', '93', '堤段所在堤防表');
INSERT INTO `资源目录` VALUES ('357', '93', '堤段管理单位表');
INSERT INTO `资源目录` VALUES ('358', '94', '险工隐患名录表');
INSERT INTO `资源目录` VALUES ('359', '94', '险工隐患基础信息表');
INSERT INTO `资源目录` VALUES ('360', '94', '险工隐患所在位置表');
INSERT INTO `资源目录` VALUES ('361', '94', '险工隐患所在河流表');
INSERT INTO `资源目录` VALUES ('362', '94', '险工隐患所在堤段表');
INSERT INTO `资源目录` VALUES ('363', '94', '险工隐患管理单位表');
INSERT INTO `资源目录` VALUES ('364', '95', '河道断面名录表');
INSERT INTO `资源目录` VALUES ('365', '95', '河道断面基础信息表');
INSERT INTO `资源目录` VALUES ('366', '95', '河道断面所在位置表');
INSERT INTO `资源目录` VALUES ('367', '95', '河道断面所在流域表');
INSERT INTO `资源目录` VALUES ('368', '95', '河道断面所在水资源分区表');
INSERT INTO `资源目录` VALUES ('369', '95', '河道断面所在河流表');
INSERT INTO `资源目录` VALUES ('370', '95', '河道断面所在湖泊表');
INSERT INTO `资源目录` VALUES ('371', '95', '河道断面所在水库表');
INSERT INTO `资源目录` VALUES ('372', '95', '河道断面所属测站表');
INSERT INTO `资源目录` VALUES ('373', '95', '河道断面所在地表水功能区表');
INSERT INTO `资源目录` VALUES ('374', '95', '河道断面所在河段表');
INSERT INTO `资源目录` VALUES ('375', '95', '河道断面管理单位表');
INSERT INTO `资源目录` VALUES ('376', '96', '行政区划名录表');
INSERT INTO `资源目录` VALUES ('377', '96', '行政区划基础信息表');
INSERT INTO `资源目录` VALUES ('378', '96', '行政区划上级行政区划表');
INSERT INTO `资源目录` VALUES ('379', '96', '行政区划水行政主管单位表');
INSERT INTO `资源目录` VALUES ('380', '97', '取水口名录表');
INSERT INTO `资源目录` VALUES ('381', '97', '取水口基础信息表');
INSERT INTO `资源目录` VALUES ('382', '97', '取水口所在位置表');
INSERT INTO `资源目录` VALUES ('383', '97', '取水口所在流域表');
INSERT INTO `资源目录` VALUES ('384', '97', '取水口所在水资源分区表');
INSERT INTO `资源目录` VALUES ('385', '97', '取水口所在河流表');
INSERT INTO `资源目录` VALUES ('386', '97', '取水口所在湖泊表');
INSERT INTO `资源目录` VALUES ('387', '97', '取水口所在水库表');
INSERT INTO `资源目录` VALUES ('388', '97', '取水口所在水闸表');
INSERT INTO `资源目录` VALUES ('389', '97', '取水口所在泵站表');
INSERT INTO `资源目录` VALUES ('390', '97', '取水口所在灌区表');
INSERT INTO `资源目录` VALUES ('391', '97', '取水口所在引调水表');
INSERT INTO `资源目录` VALUES ('392', '97', '取水口所在地表水功能区表');
INSERT INTO `资源目录` VALUES ('393', '97', '取水口所在地表水水源地表');
INSERT INTO `资源目录` VALUES ('394', '97', '取水口取水单位取用水户表');
INSERT INTO `资源目录` VALUES ('395', '98', '地下水取水井名录表');
INSERT INTO `资源目录` VALUES ('396', '98', '地下水取水井基础信息表');
INSERT INTO `资源目录` VALUES ('397', '98', '地下水取水井所在位置表');
INSERT INTO `资源目录` VALUES ('398', '98', '地下水取水井所在流域表');
INSERT INTO `资源目录` VALUES ('399', '98', '地下水取水井所在水资源分区表');
INSERT INTO `资源目录` VALUES ('400', '98', '地下水取水井所属地下水水源地表');
INSERT INTO `资源目录` VALUES ('401', '98', '地下水取水井管理单位表');
INSERT INTO `资源目录` VALUES ('402', '98', '地下水取水井管理单位涉水组织机构表');
INSERT INTO `资源目录` VALUES ('403', '99', '地下水监测井基础信息表');
INSERT INTO `资源目录` VALUES ('404', '100', '退水排污口名录表');
INSERT INTO `资源目录` VALUES ('405', '100', '退水排污口基础信息表');
INSERT INTO `资源目录` VALUES ('406', '100', '退水排污口所在位置表');
INSERT INTO `资源目录` VALUES ('407', '100', '退水排污口所在流域表');
INSERT INTO `资源目录` VALUES ('408', '100', '退水排污口所在水资源分区表');
INSERT INTO `资源目录` VALUES ('409', '100', '退水排污口排入河流表');
INSERT INTO `资源目录` VALUES ('410', '100', '退水排污口排入湖泊表');
INSERT INTO `资源目录` VALUES ('411', '100', '退水排污口排入水库表');
INSERT INTO `资源目录` VALUES ('412', '100', '退水排污口排入地表水功能区表');
INSERT INTO `资源目录` VALUES ('413', '100', '退水排污口排水单位退排水户表');
INSERT INTO `资源目录` VALUES ('414', '100', '退水排污口退排水许可机关表');
INSERT INTO `资源目录` VALUES ('415', '100', '退水排污口许可监督机关表');
INSERT INTO `资源目录` VALUES ('416', '100', '退水排污口排污单位涉水组织机构表');
INSERT INTO `资源目录` VALUES ('417', '101', '水域岸线规划基本情况表');
INSERT INTO `资源目录` VALUES ('418', '102', '考核断面基本信息表');
INSERT INTO `资源目录` VALUES ('419', '102', '考核断面所在位置表');
INSERT INTO `资源目录` VALUES ('420', '102', '考核断面所在流域表');
INSERT INTO `资源目录` VALUES ('421', '102', '考核断面所在河流表');
INSERT INTO `资源目录` VALUES ('422', '102', '考核断面管理单位表');
INSERT INTO `资源目录` VALUES ('423', '103', '施工坝基础信息表');
INSERT INTO `资源目录` VALUES ('424', '104', '路卡基础信息表');
INSERT INTO `资源目录` VALUES ('425', '105', '码头基础信息表');
INSERT INTO `资源目录` VALUES ('426', '105', '码头所在位置表');
INSERT INTO `资源目录` VALUES ('427', '105', '码头所在河流表');
INSERT INTO `资源目录` VALUES ('428', '106', '建（构）筑物基础信息表');
INSERT INTO `资源目录` VALUES ('429', '107', '桥梁名录表');
INSERT INTO `资源目录` VALUES ('430', '107', '桥梁基础信息表');
INSERT INTO `资源目录` VALUES ('431', '107', '桥梁所在位置表');
INSERT INTO `资源目录` VALUES ('432', '107', '桥梁所在河流表');
INSERT INTO `资源目录` VALUES ('433', '107', '桥梁所在河段表');
INSERT INTO `资源目录` VALUES ('434', '107', '桥梁所在蓄滞洪区表');
INSERT INTO `资源目录` VALUES ('435', '107', '桥梁管理单位表');
INSERT INTO `资源目录` VALUES ('436', '108', '管线名录表');
INSERT INTO `资源目录` VALUES ('437', '108', '管线基础信息表');
INSERT INTO `资源目录` VALUES ('438', '108', '管线所在位置表');
INSERT INTO `资源目录` VALUES ('439', '108', '管线所在河流表');
INSERT INTO `资源目录` VALUES ('440', '108', '管线所在河段表');
INSERT INTO `资源目录` VALUES ('441', '108', '管线管理单位表');
INSERT INTO `资源目录` VALUES ('442', '109', '取用水户名录表');
INSERT INTO `资源目录` VALUES ('443', '109', '取用水户基础信息表');
INSERT INTO `资源目录` VALUES ('444', '109', '取用水户所在位置表');
INSERT INTO `资源目录` VALUES ('445', '109', '取用水户所在流域表');
INSERT INTO `资源目录` VALUES ('446', '109', '取用水户所在水资源分区表');
INSERT INTO `资源目录` VALUES ('447', '109', '取用水户取水许可机关表');
INSERT INTO `资源目录` VALUES ('448', '109', '取用水户许可监督机关表');
INSERT INTO `资源目录` VALUES ('449', '109', '取用水户与涉水组织机构关系表');
INSERT INTO `资源目录` VALUES ('450', '110', '退排水户名录表');
INSERT INTO `资源目录` VALUES ('451', '110', '退排水户基础信息表');
INSERT INTO `资源目录` VALUES ('452', '110', '退排水户所在位置表');
INSERT INTO `资源目录` VALUES ('453', '110', '退排水户所在河流表');
INSERT INTO `资源目录` VALUES ('454', '110', '退排水户所在水资源分区表');
INSERT INTO `资源目录` VALUES ('455', '110', '退排水户退排水许可机关表');
INSERT INTO `资源目录` VALUES ('456', '110', '退排水户监督单位表');
INSERT INTO `资源目录` VALUES ('457', '110', '退排水户与涉水组织机构关系表');
INSERT INTO `资源目录` VALUES ('458', '111', '涉水组织机构名录表');
INSERT INTO `资源目录` VALUES ('459', '111', '涉水组织机构基础信息表');
INSERT INTO `资源目录` VALUES ('460', '111', '涉水组织机构所在位置表');
INSERT INTO `资源目录` VALUES ('461', '111', '涉水组织机构所在流域表');
INSERT INTO `资源目录` VALUES ('462', '111', '涉水组织机构所在水资源分区表');
INSERT INTO `资源目录` VALUES ('463', '112', '岸线占用单位基础信息表');
INSERT INTO `资源目录` VALUES ('464', '113', '水事案件基础信息表');
INSERT INTO `资源目录` VALUES ('465', '114', '自然人名录表');
INSERT INTO `资源目录` VALUES ('466', '114', '自然人基础信息表');
INSERT INTO `资源目录` VALUES ('467', '115', '水利行业单位名录表');
INSERT INTO `资源目录` VALUES ('468', '115', '水利行业单位基础信息表');
INSERT INTO `资源目录` VALUES ('469', '53', '政策与法规表');
INSERT INTO `资源目录` VALUES ('470', '54', '水利文献表');
INSERT INTO `资源目录` VALUES ('471', '118', '降水量表');
INSERT INTO `资源目录` VALUES ('472', '118', '降水量实时统计表');
INSERT INTO `资源目录` VALUES ('473', '118', '降水量记载表');
INSERT INTO `资源目录` VALUES ('474', '118', '日降水量表');
INSERT INTO `资源目录` VALUES ('475', '118', '分钟时段最大降水量表');
INSERT INTO `资源目录` VALUES ('476', '118', '小时时段最大降水量表');
INSERT INTO `资源目录` VALUES ('477', '118', '日时段最大降水量表');
INSERT INTO `资源目录` VALUES ('478', '118', '日降水量多年均值表');
INSERT INTO `资源目录` VALUES ('479', '118', '行政区域日降水量多年均值表');
INSERT INTO `资源目录` VALUES ('480', '118', '旬月年降水量表');
INSERT INTO `资源目录` VALUES ('481', '118', '旬月降水量系列表');
INSERT INTO `资源目录` VALUES ('482', '118', '旬月降水量多年均值表');
INSERT INTO `资源目录` VALUES ('483', '119', '河道水情表');
INSERT INTO `资源目录` VALUES ('484', '119', '河道水情实时多日均值表');
INSERT INTO `资源目录` VALUES ('485', '119', '河道水情极值实时表');
INSERT INTO `资源目录` VALUES ('486', '119', '潮汐水情表');
INSERT INTO `资源目录` VALUES ('487', '119', '潮汐水情实时多日均值表');
INSERT INTO `资源目录` VALUES ('488', '119', '潮汐水情极值实时表');
INSERT INTO `资源目录` VALUES ('489', '119', '日平均水位表');
INSERT INTO `资源目录` VALUES ('490', '119', '水位流量多年日平均统计表');
INSERT INTO `资源目录` VALUES ('491', '119', '旬月年水位表');
INSERT INTO `资源目录` VALUES ('492', '119', '水位流量旬月均值系列表');
INSERT INTO `资源目录` VALUES ('493', '119', '水位流量多年旬月平均统计表');
INSERT INTO `资源目录` VALUES ('494', '119', '水位流量旬月极值系列表');
INSERT INTO `资源目录` VALUES ('495', '119', '水位流量年极值系列表');
INSERT INTO `资源目录` VALUES ('496', '120', '考核断面水质监测表');
INSERT INTO `资源目录` VALUES ('497', '120', '考核断面水质统计信息表');
INSERT INTO `资源目录` VALUES ('498', '121', '灌区监测信息表');
INSERT INTO `资源目录` VALUES ('499', '121', '灌区日统计信息表');
INSERT INTO `资源目录` VALUES ('500', '121', '灌区月统计信息表');
INSERT INTO `资源目录` VALUES ('501', '121', '灌区年统计信息表');
INSERT INTO `资源目录` VALUES ('502', '122', '地下水监测井水位监测表');
INSERT INTO `资源目录` VALUES ('503', '122', '地下水监测井日统计信息表');
INSERT INTO `资源目录` VALUES ('504', '122', '地下水监测井月统计信息表');
INSERT INTO `资源目录` VALUES ('505', '122', '地下水监测井年统计信息表');
INSERT INTO `资源目录` VALUES ('506', '123', '水功能区水质监测信息表');
INSERT INTO `资源目录` VALUES ('507', '123', '水功能区水质达标率月度统计表');
INSERT INTO `资源目录` VALUES ('508', '123', '水功能区水质达标率季度统计表');
INSERT INTO `资源目录` VALUES ('509', '123', '水功能区水质达标率年度统计表');
INSERT INTO `资源目录` VALUES ('510', '124', '积水点监测表');
INSERT INTO `资源目录` VALUES ('511', '125', '堰闸水情监测表');
INSERT INTO `资源目录` VALUES ('512', '125', '堰闸水情极值实时表');
INSERT INTO `资源目录` VALUES ('513', '125', '水闸工情监测表');
INSERT INTO `资源目录` VALUES ('514', '126', '泵站水情监测表');
INSERT INTO `资源目录` VALUES ('515', '126', '泵站工情监测信息表');
INSERT INTO `资源目录` VALUES ('516', '126', '堰闸（泵）站水情实时多日均值表');
INSERT INTO `资源目录` VALUES ('517', '127', '堤防安全监测信息表');
INSERT INTO `资源目录` VALUES ('518', '128', '圩垸监测信息表');
INSERT INTO `资源目录` VALUES ('519', '129', '涵洞工情监测信息表');
INSERT INTO `资源目录` VALUES ('520', '130', '水库水情表');
INSERT INTO `资源目录` VALUES ('521', '130', '水库水情实时多日均值表');
INSERT INTO `资源目录` VALUES ('522', '130', '水库水情极值实时表');
INSERT INTO `资源目录` VALUES ('523', '130', '水库工情表');
INSERT INTO `资源目录` VALUES ('524', '130', '水库闸门工情表');
INSERT INTO `资源目录` VALUES ('525', '130', '水库电站监测表');
INSERT INTO `资源目录` VALUES ('526', '130', '水库大坝安全监测信息表');
INSERT INTO `资源目录` VALUES ('527', '131', '堤段监测信息表');
INSERT INTO `资源目录` VALUES ('528', '132', '取用水户取水量实时监测表');
INSERT INTO `资源目录` VALUES ('529', '132', '取用水户日取水量统计表');
INSERT INTO `资源目录` VALUES ('530', '132', '取用水户月取水量统计表');
INSERT INTO `资源目录` VALUES ('531', '132', '取用水户年取水量统计表');
INSERT INTO `资源目录` VALUES ('532', '132', '地表水取水口实时取水量监测表');
INSERT INTO `资源目录` VALUES ('533', '132', '地表水取水口日取水量统计表');
INSERT INTO `资源目录` VALUES ('534', '132', '地表水取水口月取水量统计表');
INSERT INTO `资源目录` VALUES ('535', '132', '地表水取水口年取水量统计表');
INSERT INTO `资源目录` VALUES ('536', '133', '退排水户退排水量监测表');
INSERT INTO `资源目录` VALUES ('537', '133', '退排水户退排水量日统计表');
INSERT INTO `资源目录` VALUES ('538', '133', '退排水户退排水量月统计表');
INSERT INTO `资源目录` VALUES ('539', '133', '退排水户退排水量年统计表');
INSERT INTO `资源目录` VALUES ('540', '133', '入河湖排污口排水量监测表');
INSERT INTO `资源目录` VALUES ('541', '133', '入河湖排污口日排水量统计表');
INSERT INTO `资源目录` VALUES ('542', '133', '入河湖排污口月排水量统计表');
INSERT INTO `资源目录` VALUES ('543', '133', '入河湖排污口年排水量统计表');
INSERT INTO `资源目录` VALUES ('544', '134', '地下水取水井实时取水量表');
INSERT INTO `资源目录` VALUES ('545', '134', '地下水取水井日取水量统计表');
INSERT INTO `资源目录` VALUES ('546', '134', '地下水取水井月取水量统计表');
INSERT INTO `资源目录` VALUES ('547', '134', '地下水取水井年取水量统计表');
INSERT INTO `资源目录` VALUES ('548', '135', '自来水厂实时出厂水量信息表');
INSERT INTO `资源目录` VALUES ('549', '135', '自来水厂日出厂水量统计表');
INSERT INTO `资源目录` VALUES ('550', '135', '自来水厂月出厂水量统计表');
INSERT INTO `资源目录` VALUES ('551', '135', '自来水厂年出水厂量统计表');
INSERT INTO `资源目录` VALUES ('552', '135', '自来水厂年度售水量统计表');
INSERT INTO `资源目录` VALUES ('553', '135', '自来水厂出厂水质监测表');
INSERT INTO `资源目录` VALUES ('554', '135', '出厂水质原始数据表');
INSERT INTO `资源目录` VALUES ('555', '135', '自来水厂年出厂水质达标率表');
INSERT INTO `资源目录` VALUES ('556', '136', '城镇污水处理厂运行月度统计表');
INSERT INTO `资源目录` VALUES ('557', '136', '城镇污水处理厂运行季度统计表');
INSERT INTO `资源目录` VALUES ('558', '136', '城镇污水处理厂运行年统计表');
INSERT INTO `资源目录` VALUES ('559', '136', '农村生活污水设施运行月度统计表');
INSERT INTO `资源目录` VALUES ('560', '136', '农村生活污水设施运行季度统计表');
INSERT INTO `资源目录` VALUES ('561', '136', '农村生活污水设施运行年统计表');
INSERT INTO `资源目录` VALUES ('562', '137', '气象降水量表');
INSERT INTO `资源目录` VALUES ('563', '137', '风向风力表');
INSERT INTO `资源目录` VALUES ('564', '138', '水情预报成果注释表');
INSERT INTO `资源目录` VALUES ('565', '138', '水情预报成果表');
INSERT INTO `资源目录` VALUES ('566', '138', '调度预报成果表');
INSERT INTO `资源目录` VALUES ('567', '138', '潮位预报成果表');
INSERT INTO `资源目录` VALUES ('568', '138', '天文潮预报成果表');
INSERT INTO `资源目录` VALUES ('569', '138', '降雨预警信息表');
INSERT INTO `资源目录` VALUES ('570', '138', '水位预警信息表');
INSERT INTO `资源目录` VALUES ('571', '138', '含沙量预报表');
INSERT INTO `资源目录` VALUES ('572', '138', '冰情预报表');
INSERT INTO `资源目录` VALUES ('573', '138', '气象天气预报表');
INSERT INTO `资源目录` VALUES ('574', '139', '防汛机构基本信息表');
INSERT INTO `资源目录` VALUES ('575', '139', '抢险队伍基本信息表');
INSERT INTO `资源目录` VALUES ('576', '139', '防汛物资基本信息表');
INSERT INTO `资源目录` VALUES ('577', '139', '避灾场所基本信息表');
INSERT INTO `资源目录` VALUES ('578', '140', '积水点基本信息表');
INSERT INTO `资源目录` VALUES ('579', '140', '积水点所在位置表');
INSERT INTO `资源目录` VALUES ('580', '140', '积水点所在流域表');
INSERT INTO `资源目录` VALUES ('581', '140', '积水点所属河流表');
INSERT INTO `资源目录` VALUES ('582', '140', '积水点管理单位表');
INSERT INTO `资源目录` VALUES ('583', '141', '测站维护情况表');
INSERT INTO `资源目录` VALUES ('584', '142', '防汛预案');
INSERT INTO `资源目录` VALUES ('585', '125', '水闸安全鉴定信息表');
INSERT INTO `资源目录` VALUES ('586', '125', '水闸维修养护信息表');
INSERT INTO `资源目录` VALUES ('587', '125', '水闸管护经费统计表');
INSERT INTO `资源目录` VALUES ('588', '125', '水闸管护人员信息表');
INSERT INTO `资源目录` VALUES ('589', '126', '泵站建设维修历史情况表');
INSERT INTO `资源目录` VALUES ('590', '126', '泵站管护经费统计表');
INSERT INTO `资源目录` VALUES ('591', '127', '堤防维修养护历史情况表');
INSERT INTO `资源目录` VALUES ('592', '127', '堤防管护经费统计表');
INSERT INTO `资源目录` VALUES ('593', '131', '堤段运行管理信息表');
INSERT INTO `资源目录` VALUES ('594', '147', '河道规划情况表');
INSERT INTO `资源目录` VALUES ('595', '147', '水闸规划情况表');
INSERT INTO `资源目录` VALUES ('596', '147', '泵站规划情况表');
INSERT INTO `资源目录` VALUES ('597', '147', '堤防规划情况表');
INSERT INTO `资源目录` VALUES ('598', '148', '建设项目计划信息表');
INSERT INTO `资源目录` VALUES ('599', '148', '建设项目包含建设工程表');
INSERT INTO `资源目录` VALUES ('600', '148', '建设工程基本信息表');
INSERT INTO `资源目录` VALUES ('601', '148', '建设工程实施过程表');
INSERT INTO `资源目录` VALUES ('602', '148', '建设工程投资统计信息表');
INSERT INTO `资源目录` VALUES ('603', '149', '取水许可统计表');
INSERT INTO `资源目录` VALUES ('604', '150', '水资源管理大事统计表');
INSERT INTO `资源目录` VALUES ('605', '151', '水源地保护信息表');
INSERT INTO `资源目录` VALUES ('606', '63', '用水定额管理信息表');
INSERT INTO `资源目录` VALUES ('607', '63', '计划用水户实际用水量、产量产值统计表');
INSERT INTO `资源目录` VALUES ('608', '63', '节水单位信息表');
INSERT INTO `资源目录` VALUES ('609', '153', '节水型社会创建信息表');
INSERT INTO `资源目录` VALUES ('610', '154', '河长基本信息表');
INSERT INTO `资源目录` VALUES ('611', '154', '一河一档信息表');
INSERT INTO `资源目录` VALUES ('612', '154', '一河一策信息表');
INSERT INTO `资源目录` VALUES ('613', '154', '河长制工作情况表');
INSERT INTO `资源目录` VALUES ('614', '154', '事项基本情况表');
INSERT INTO `资源目录` VALUES ('615', '154', '事项实施进度统计表');
INSERT INTO `资源目录` VALUES ('616', '154', '河长巡河记录表');
INSERT INTO `资源目录` VALUES ('617', '154', '河长办派发任务表');
INSERT INTO `资源目录` VALUES ('618', '154', '河长办派发任务执行情况表');
INSERT INTO `资源目录` VALUES ('619', '155', '水域岸线日常监管信息表');
INSERT INTO `资源目录` VALUES ('620', '155', '涉河项目审批信息表');
INSERT INTO `资源目录` VALUES ('621', '155', '水域岸线监管工程表');
INSERT INTO `资源目录` VALUES ('622', '155', '涉河项目事中监管情况表');
INSERT INTO `资源目录` VALUES ('623', '156', '河道管护情况表');
INSERT INTO `资源目录` VALUES ('624', '156', '河道疏浚整治统计表');
INSERT INTO `资源目录` VALUES ('625', '156', '河道管护经费信息表');
INSERT INTO `资源目录` VALUES ('626', '157', '采砂量统计信息表');
INSERT INTO `资源目录` VALUES ('627', '158', '建、构筑物审批信息表');
INSERT INTO `资源目录` VALUES ('628', '158', '建、构筑物监管信息表');
INSERT INTO `资源目录` VALUES ('629', '159', '河道保洁基本情况表');
INSERT INTO `资源目录` VALUES ('630', '159', '河道垃圾打捞量日统计表');
INSERT INTO `资源目录` VALUES ('631', '159', '河道垃圾打捞量周统计表');
INSERT INTO `资源目录` VALUES ('632', '159', '河道垃圾打捞量月统计表');
INSERT INTO `资源目录` VALUES ('633', '159', '河道垃圾打捞量年统计表');
INSERT INTO `资源目录` VALUES ('634', '160', '水利桥梁基本情况表');
INSERT INTO `资源目录` VALUES ('635', '161', '路卡开关情况日报表');
INSERT INTO `资源目录` VALUES ('636', '162', '建设项目环境影响信息表');
INSERT INTO `资源目录` VALUES ('637', '163', '巡检任务信息表');
INSERT INTO `资源目录` VALUES ('638', '163', '巡检点信息表');
INSERT INTO `资源目录` VALUES ('639', '163', '巡检点包含巡检项目表');
INSERT INTO `资源目录` VALUES ('640', '163', '巡检作业信息表');
INSERT INTO `资源目录` VALUES ('641', '163', '巡检反馈信息表');
INSERT INTO `资源目录` VALUES ('642', '163', '巡检任务月统计信息表');
INSERT INTO `资源目录` VALUES ('643', '163', '巡检任务年统计信息表');
INSERT INTO `资源目录` VALUES ('644', '163', '设备维修记录表');
INSERT INTO `资源目录` VALUES ('645', '164', '水政执法队伍基本信息表');
INSERT INTO `资源目录` VALUES ('646', '164', '水事案件查处情况统计表');
INSERT INTO `资源目录` VALUES ('647', '165', '许可审批事项统计表');
INSERT INTO `资源目录` VALUES ('648', '166', '公文信息表');
INSERT INTO `资源目录` VALUES ('649', '166', '通知公告统计表');
INSERT INTO `资源目录` VALUES ('650', '166', '信访信息表');
INSERT INTO `资源目录` VALUES ('651', '166', '政务公开信息表');
INSERT INTO `资源目录` VALUES ('652', '166', '计划总结文档表');
INSERT INTO `资源目录` VALUES ('653', '167', '财务信息表');
INSERT INTO `资源目录` VALUES ('654', '168', '组织机构信息表');
INSERT INTO `资源目录` VALUES ('655', '168', '人事信息表');
INSERT INTO `资源目录` VALUES ('656', '169', '科技管理表');
INSERT INTO `资源目录` VALUES ('657', '170', '纪检监察信息表');
INSERT INTO `资源目录` VALUES ('658', '171', '安全监督信息表');
INSERT INTO `资源目录` VALUES ('659', '172', '机关管理表');
INSERT INTO `资源目录` VALUES ('660', '173', '测绘测量成果统计表');
INSERT INTO `资源目录` VALUES ('661', '174', '河道普查成果表');
INSERT INTO `资源目录` VALUES ('662', '174', '水闸普查成果表');
INSERT INTO `资源目录` VALUES ('663', '174', '泵站普查成果表');
INSERT INTO `资源目录` VALUES ('664', '174', '堤防普查成果表');
